In [3]:
%load_ext autoreload 
# il s’applique à tous les 
#fichiers .py que le notebook a importés et sa permet 
# de verifier si tous marche 
%autoreload 2
import sys; sys.path.append("..")
#Permet au notebook, qui est dans notebooks, 
#de trouver le dossier src situé au-dessus
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
import yfinance as yf
test = yf.download("TTE.PA", start="2024-01-01", end="2024-02-01", auto_adjust=True)

[*********************100%***********************]  1 of 1 completed

In [5]:
test

Price           Close       High        Low       Open   Volume
Ticker         TTE.PA     TTE.PA     TTE.PA     TTE.PA   TTE.PA
Date
2024-01-02  53.505131  53.781331  53.203035  53.384290  4444831
2024-01-03  53.289352  53.574182  52.883683  53.436082  3492054
2024-01-04  53.928062  54.376888  53.556918  53.669126  3956219
2024-01-05  53.945324  54.117950  53.444710  53.703650  2376845
2024-01-08  52.262226  53.556914  52.262226  53.513758  3900649
2024-01-09  51.891083  52.797364  51.891083  52.521164  3053098
2024-01-10  51.588993  52.046448  51.528575  51.787511  2757095
2024-01-11  51.338684  51.942872  51.235110  51.537202  4264632
2024-01-12  51.908348  52.512536  51.865192  52.003292  3034026
2024-01-15  51.735725  52.020558  51.494051  51.899721  2068080
2024-01-16  51.424999  51.865192  51.114274  51.355948  3483825
2024-01-17  50.285667  50.708600  49.862738  50.691337  4637885
2024-01-18  50.501450  50.553238  49.992206  50.121676  3715641
2024-01-19  50.302933  51.114272  50.294303  50.881228  3426875
2024-01-22  49.845474  50.717229  49.586537  50.389244  4019036
2024-01-23  50.164829  50.466925  49.854104  50.328825  3795632
2024-01-24  50.803547  50.933014  49.983577  50.182096  4325754
2024-01-25  50.872593  51.494044  50.674075  51.088374  3108343
2024-01-26  51.459522  52.029185  51.373211  51.588992  3519412
2024-01-29  51.968765  52.762842  51.735721  52.357172  3413933
2024-01-30  52.158657  52.296757  51.770250  51.873824  2824518
2024-01-31  51.873821  52.702424  51.873821  52.650635  5020356

In [6]:
y=test["Close"]
print(y.head())

Ticker         TTE.PA
Date
2024-01-02  53.505131
2024-01-03  53.289352
2024-01-04  53.928062
2024-01-05  53.945324
2024-01-08  52.262226

In [7]:
import yfinance as yf
tickers = ["TTE.PA", "BNP.PA", "MC.PA", "AIR.PA", "SAN.PA"]
tes=yf.download(tickers ,start ="2005-01-01", end= "2025-12-31", auto_adjust= True )
y=tes["Close"]
print(y.head())

[*********************100%***********************]  5 of 5 completed

Ticker         AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03  15.835871  17.847841  36.960773  24.980865  11.679474
2005-01-04  15.542073  17.980783  36.764870  24.896610  11.635846
2005-01-05  15.409863  17.881077  36.209808  24.538538  11.526752
2005-01-06  15.865252  18.146965  36.340405  24.285780  11.614025
2005-01-07  16.100296  18.346380  36.601612  24.370028  11.650386

In [8]:
r=y.isna().sum()
t=len(y)
print(t)
print(r)

5375
Ticker
AIR.PA    0
BNP.PA    0
MC.PA     0
SAN.PA    0
TTE.PA    0
dtype: int64

In [9]:
y.to_csv("../data/prices.csv")

In [10]:
prices=pd.read_csv("../data/prices.csv",index_col=0, parse_dates=True)

In [11]:
print(prices.head())

               AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03  15.835871  17.847841  36.960773  24.980865  11.679474
2005-01-04  15.542073  17.980783  36.764870  24.896610  11.635846
2005-01-05  15.409863  17.881077  36.209808  24.538538  11.526752
2005-01-06  15.865252  18.146965  36.340405  24.285780  11.614025
2005-01-07  16.100296  18.346380  36.601612  24.370028  11.650386

In [12]:
from src.data import load_prices

tickers = ["TTE.PA", "BNP.PA", "MC.PA", "AIR.PA", "SAN.PA"]
prices = load_prices(tickers, "2005-01-01", "2025-12-31", "../data/prices.csv")
prices.head()

               AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03  15.835871  17.847841  36.960773  24.980865  11.679474
2005-01-04  15.542073  17.980783  36.764870  24.896610  11.635846
2005-01-05  15.409863  17.881077  36.209808  24.538538  11.526752
2005-01-06  15.865252  18.146965  36.340405  24.285780  11.614025
2005-01-07  16.100296  18.346380  36.601612  24.370028  11.650386

In [13]:
test = load_prices(tickers, "2024-01-01", "2024-02-01", "../data/test.csv")
test.head()

[*********************100%***********************]  5 of 5 completed

Ticker          AIR.PA     BNP.PA       MC.PA     SAN.PA     TTE.PA
Date
2024-01-02  133.345276  50.696484  681.810913  79.159782  53.505131
2024-01-03  129.456665  49.344254  655.783325  80.109108  53.289352
2024-01-04  131.551971  50.336422  658.046570  80.849403  53.928062
2024-01-05  131.853989  50.408440  649.653625  81.415512  53.945324
2024-01-08  135.157425  50.520454  651.916809  81.981628  52.262226

In [14]:
prices.head()

               AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03  15.835871  17.847841  36.960773  24.980865  11.679474
2005-01-04  15.542073  17.980783  36.764870  24.896610  11.635846
2005-01-05  15.409863  17.881077  36.209808  24.538538  11.526752
2005-01-06  15.865252  18.146965  36.340405  24.285780  11.614025
2005-01-07  16.100296  18.346380  36.601612  24.370028  11.650386

In [15]:
prices.shift(1).head()

               AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03        NaN        NaN        NaN        NaN        NaN
2005-01-04  15.835871  17.847841  36.960773  24.980865  11.679474
2005-01-05  15.542073  17.980783  36.764870  24.896610  11.635846
2005-01-06  15.409863  17.881077  36.209808  24.538538  11.526752
2005-01-07  15.865252  18.146965  36.340405  24.285780  11.614025

In [16]:
t= prices
t1= prices.shift(1)
returns=np.log(t/t1)
print(returns.head())

              AIR.PA    BNP.PA     MC.PA    SAN.PA    TTE.PA
Date
2005-01-03       NaN       NaN       NaN       NaN       NaN
2005-01-04 -0.018727  0.007421 -0.005314 -0.003378 -0.003742
2005-01-05 -0.008543 -0.005561 -0.015213 -0.014487 -0.009420
2005-01-06  0.029124  0.014760  0.003600 -0.010354  0.007543
2005-01-07  0.014706  0.010929  0.007162  0.003463  0.003126

In [17]:
returns=returns.dropna()
print(returns.head())

              AIR.PA    BNP.PA     MC.PA    SAN.PA    TTE.PA
Date
2005-01-04 -0.018727  0.007421 -0.005314 -0.003378 -0.003742
2005-01-05 -0.008543 -0.005561 -0.015213 -0.014487 -0.009420
2005-01-06  0.029124  0.014760  0.003600 -0.010354  0.007543
2005-01-07  0.014706  0.010929  0.007162  0.003463  0.003126
2005-01-10  0.016739  0.001810 -0.006264  0.005172  0.001871

In [ ]:
from src.data import load_prices, compute_returns
returns = compute_returns(prices)
returns.head()

              AIR.PA    BNP.PA     MC.PA    SAN.PA    TTE.PA
Date
2005-01-04 -0.018727  0.007421 -0.005314 -0.003378 -0.003742
2005-01-05 -0.008543 -0.005561 -0.015213 -0.014487 -0.009420
2005-01-06  0.029124  0.014760  0.003600 -0.010354  0.007543
2005-01-07  0.014706  0.010929  0.007162  0.003463  0.003126
2005-01-10  0.016739  0.001810 -0.006264  0.005172  0.001871

In [19]:
print(len(prices),len(returns))

5375 5374

In [21]:
from src.data import portfolio_losses

In [23]:
print(losses.deah())

NameError: name 'losses' is not defined