In [8]:
%load_ext autoreload 
# il s’applique à tous les 
#fichiers .py que le notebook a importés et sa permet 
# de verifier si tous marche 
%autoreload 2
import sys; sys.path.append("..")
#Permet au notebook, qui est dans notebooks, 
#de trouver le dossier src situé au-dessus
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
import yfinance as yf
test = yf.download("TTE.PA", start="2024-01-01", end="2024-02-01", auto_adjust=True)

[*********************100%***********************]  1 of 1 completed

In [10]:
test

Price           Close       High        Low       Open   Volume
Ticker         TTE.PA     TTE.PA     TTE.PA     TTE.PA   TTE.PA
Date
2024-01-02  53.505135  53.781334  53.203039  53.384294  4444831
2024-01-03  53.289349  53.574178  52.883679  53.436078  3492054
2024-01-04  53.928059  54.376884  53.556915  53.669122  3956219
2024-01-05  53.945320  54.117946  53.444706  53.703646  2376845
2024-01-08  52.262226  53.556914  52.262226  53.513758  3900649
2024-01-09  51.891087  52.797367  51.891087  52.521168  3053098
2024-01-10  51.588989  52.046445  51.528571  51.787508  2757095
2024-01-11  51.338684  51.942872  51.235110  51.537202  4264632
2024-01-12  51.908352  52.512540  51.865196  52.003296  3034026
2024-01-15  51.735725  52.020558  51.494051  51.899721  2068080
2024-01-16  51.424999  51.865192  51.114274  51.355948  3483825
2024-01-17  50.285664  50.708596  49.862734  50.691333  4637885
2024-01-18  50.501453  50.553242  49.992209  50.121680  3715641
2024-01-19  50.302933  51.114272  50.294303  50.881228  3426875
2024-01-22  49.845478  50.717233  49.586541  50.389248  4019036
2024-01-23  50.164829  50.466925  49.854104  50.328825  3795632
2024-01-24  50.803547  50.933014  49.983577  50.182096  4325754
2024-01-25  50.872597  51.494048  50.674078  51.088378  3108343
2024-01-26  51.459522  52.029185  51.373211  51.588992  3519412
2024-01-29  51.968765  52.762842  51.735721  52.357172  3413933
2024-01-30  52.158653  52.296753  51.770246  51.873820  2824518
2024-01-31  51.873821  52.702424  51.873821  52.650635  5020356

In [11]:
y=test["Close"]
print(y.head())

Ticker         TTE.PA
Date
2024-01-02  53.505135
2024-01-03  53.289349
2024-01-04  53.928059
2024-01-05  53.945320
2024-01-08  52.262226

In [12]:
import yfinance as yf
tickers = ["TTE.PA", "BNP.PA", "MC.PA", "AIR.PA", "SAN.PA"]
tes=yf.download(tickers ,start ="2005-01-01", end= "2025-12-31", auto_adjust= True )
y=tes["Close"]
print(y.head())

[*********************100%***********************]  5 of 5 completed

Ticker         AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03  15.835877  17.847839  36.960773  24.980858  11.679480
2005-01-04  15.542072  17.980780  36.764862  24.896605  11.635842
2005-01-05  15.409862  17.881073  36.209805  24.538536  11.526760
2005-01-06  15.865259  18.146959  36.340408  24.285780  11.614023
2005-01-07  16.100298  18.346380  36.601604  24.370029  11.650386

In [13]:
r=y.isna().sum()
t=len(y)
print(t)
print(r)

5375
Ticker
AIR.PA    0
BNP.PA    0
MC.PA     0
SAN.PA    0
TTE.PA    0
dtype: int64

In [14]:
y.to_csv("../data/prices.csv")

In [21]:
prices=pd.read_csv("../data/prices.csv",index_col=0, parse_dates=True)

In [22]:
print(prices.head())

               AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03  15.835877  17.847839  36.960773  24.980858  11.679480
2005-01-04  15.542072  17.980780  36.764862  24.896605  11.635842
2005-01-05  15.409862  17.881073  36.209805  24.538536  11.526760
2005-01-06  15.865259  18.146959  36.340408  24.285780  11.614023
2005-01-07  16.100298  18.346380  36.601604  24.370029  11.650386

In [23]:
from src.data import load_prices

tickers = ["TTE.PA", "BNP.PA", "MC.PA", "AIR.PA", "SAN.PA"]
prices = load_prices(tickers, "2005-01-01", "2025-12-31", "../data/prices.csv")
prices.head()

               AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03  15.835877  17.847839  36.960773  24.980858  11.679480
2005-01-04  15.542072  17.980780  36.764862  24.896605  11.635842
2005-01-05  15.409862  17.881073  36.209805  24.538536  11.526760
2005-01-06  15.865259  18.146959  36.340408  24.285780  11.614023
2005-01-07  16.100298  18.346380  36.601604  24.370029  11.650386

In [25]:
test = load_prices(tickers, "2024-01-01", "2024-02-01", "../data/test.csv")
test.head()

                AIR.PA     BNP.PA       MC.PA     SAN.PA     TTE.PA
Date
2024-01-02  133.345276  50.696487  681.810913  79.159782  53.505135
2024-01-03  129.456665  49.344254  655.783264  80.109108  53.289349
2024-01-04  131.551971  50.336422  658.046509  80.849403  53.928059
2024-01-05  131.853989  50.408436  649.653625  81.415520  53.945320
2024-01-08  135.157425  50.520454  651.916809  81.981621  52.262226

In [ ]:
prices.head()

               AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03  15.835877  17.847839  36.960773  24.980858  11.679480
2005-01-04  15.542072  17.980780  36.764862  24.896605  11.635842
2005-01-05  15.409862  17.881073  36.209805  24.538536  11.526760
2005-01-06  15.865259  18.146959  36.340408  24.285780  11.614023
2005-01-07  16.100298  18.346380  36.601604  24.370029  11.650386

In [27]:
prices.shift(1).head()

               AIR.PA     BNP.PA      MC.PA     SAN.PA     TTE.PA
Date
2005-01-03        NaN        NaN        NaN        NaN        NaN
2005-01-04  15.835877  17.847839  36.960773  24.980858  11.679480
2005-01-05  15.542072  17.980780  36.764862  24.896605  11.635842
2005-01-06  15.409862  17.881073  36.209805  24.538536  11.526760
2005-01-07  15.865259  18.146959  36.340408  24.285780  11.614023

In [28]:
t= prices
t1= prices.shift(1)
returns=np.log(t/t1)
print(returns.head())

              AIR.PA    BNP.PA     MC.PA    SAN.PA    TTE.PA
Date
2005-01-03       NaN       NaN       NaN       NaN       NaN
2005-01-04 -0.018727  0.007421 -0.005315 -0.003378 -0.003743
2005-01-05 -0.008543 -0.005561 -0.015213 -0.014487 -0.009419
2005-01-06  0.029124  0.014760  0.003600 -0.010354  0.007542
2005-01-07  0.014706  0.010929  0.007162  0.003463  0.003126

In [30]:
returns=returns.dropna()
print(returns.head())

              AIR.PA    BNP.PA     MC.PA    SAN.PA    TTE.PA
Date
2005-01-04 -0.018727  0.007421 -0.005315 -0.003378 -0.003743
2005-01-05 -0.008543 -0.005561 -0.015213 -0.014487 -0.009419
2005-01-06  0.029124  0.014760  0.003600 -0.010354  0.007542
2005-01-07  0.014706  0.010929  0.007162  0.003463  0.003126
2005-01-10  0.016738  0.001810 -0.006264  0.005173  0.001871

In [31]:
from src.data import load_prices, compute_returns 
returns = compute_returns(prices)
returns.head()

              AIR.PA    BNP.PA     MC.PA    SAN.PA    TTE.PA
Date
2005-01-04 -0.018727  0.007421 -0.005315 -0.003378 -0.003743
2005-01-05 -0.008543 -0.005561 -0.015213 -0.014487 -0.009419
2005-01-06  0.029124  0.014760  0.003600 -0.010354  0.007542
2005-01-07  0.014706  0.010929  0.007162  0.003463  0.003126
2005-01-10  0.016738  0.001810 -0.006264  0.005173  0.001871

In [32]:
print(len(prices),len(returns))

5375 5374